site_name: Тестовый стенд для документации
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      name: "default"
    - media: "(prefers-color-scheme: dark)"
      name: "dark"

extra:
  theme_switcher: true

docs_dir: docs
plugins:
  - search
  - macros:
      module_name: macros
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
nav:
  - Home: index.md
  - BankDTO Mapping example: mapping_table.md
  - Диаграммы:
      - Sequence: Группа 1/diagrams.md
      - Activity: Группа 1/activity_diagram.md
