site_name: Тестовый стенд для документации
theme:
  icon:
    repo: fontawesome/brands/github-alt
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)"
      name: "default"
    - media: "(prefers-color-scheme: dark)"
      name: "dark"
repo_url: https://github.com/aggromarus/Test

extra:
  theme_switcher: true
  toc_title: "Мой собственный заголовок"
docs_dir: docs
plugins:
  - search
  - macros:
      module_name: macros
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
      interaction:
        enabled: true
nav:
  - Домашняя страница: index.md
  - BankDTO Mapping example: mapping_table.md
  - Диаграммы:
      - Sequence: Group-1/diagrams.md
      - Activity: Group-1/activity_diagram.md
      - Classes: Group-1/diagramm_classes.md
