site_name: Docs
theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
docs_dir: docs
plugins:
  - search
  - macros:
      module_name: macros
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
nav:
  - Home: index.md
  - First Mapping Page: about.md
  - BankDTO Mapping example: mapping_table.md
  - DiagramsPage: diagrams.md
