name: Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install MkDocs
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Check current directory
        run: |
          pwd
          ls -la

      - name: Pull latest changes
        run: |
          git gc --prune=now
          git pull origin main  # Обновление локальных файлов с удалённого репозитория

      - name: Build MkDocs site
        run: |
          source venv/bin/activate
          mkdocs build
          deactivate
          ls -al /home/runner/work/Test/Test/site

      - name: Set up SSH for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          debug: true
          script: |
            rm -rf /var/www/html/*
            cp -r /home/runner/work/Test/Test/site /var/www/html/